//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoKolcsonzoApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kolcsonzesek
    {
        private int kolcsonzesID;
        public int KolcsonzesID
        {
            get { return kolcsonzesID; }
            set
            {
                if (value > 0 && value < 10)
                    kolcsonzesID = value;
                else throw new Exception("Hibás kolcsonzesID :" + value);
            }
        }
        public int VevokID { get; set; }
        public int AutoID { get; set; }
        public System.DateTime KolcsonzesIdeje { get; set; }
    
        public virtual Autok Autok { get; set; }
        public virtual Vevok Vevok { get; set; }
    }
}
