//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoKolcsonzoApp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AutokolcsonzoEntities : DbContext
    {
        public AutokolcsonzoEntities()
            : base("name=AutokolcsonzoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Autok> Autoks { get; set; }
        public virtual DbSet<Kolcsonzesek> Kolcsonzeseks { get; set; }
        public virtual DbSet<Vevok> Vevoks { get; set; }
    }
}
