//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoKolcsonzoApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kolcsonzesek
    {
        public int KolcsonzesID { get; set; }
        public int VevokID { get; set; }
        public int AutoID { get; set; }
        public System.DateTime KolcsonzesIdeje { get; set; }
    
        public virtual Autok Autok { get; set; }
        public virtual Vevok Vevok { get; set; }
    }
}
